name: Rust-makepkg-Arch

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: archlinux-latest

    steps:
    
    - uses: actions/checkout@v4
    - uses: docker://archlinux:latest
    - name: Manual build test 
      run: cargo build --verbose
    
    - name: Cargo tests 
      run: cargo test --verbose
      
    - name: Test makepkg build 
      run: bash -c "
            pacman -Sy --noconfirm base-devel git alsa-lib libx11 rustup &&
            useradd -m builder &&
            chown -R builder:builder /github/workspace &&
            cd /github/workspace/aur &&
            sudo -u builder bash -c '
            rustup default stable &&
            makepkg -sf --noconfirm --nocheck --syncdeps'"