name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu, archlinux]

    steps:
    - uses: actions/checkout@v4

    - name: Setup environment (Ubuntu)
      if: matrix.os == 'ubuntu'
      run: |
        sudo apt update
        sudo apt install -y libasound2-dev libx11-dev

    - name: Setup environment and test makepkg build
      if: matrix.os == 'archlinux'
      uses: docker://archlinux:latest
      with:
        args: |
          bash -c "
            pacman -Sy --noconfirm base-devel git rustup &&
            useradd -m builder &&
            chown -R builder:builder /github/workspace &&
            cd /github/workspace/aur
            sudo -u builder makepkg -sf
          "

    - name: Build (Ubuntu)
      if: matrix.os == 'ubuntu'
      run: cargo build --verbose --release

    - name: Test (Ubuntu)
      if: matrix.os == 'ubuntu'
      run: cargo test --verbose
